
address={
'Krabi':'กระบี่',
'Bangkok':'กรุงเทพมหานคร',
'Kanchanaburi':'กาญจนบุรี',
'Kalasin':'กาฬสินธุ์',
'Kamphaeng Phet':'กำแพงเพชร',
'Khon Kaen':'ขอนแก่น',
'Chanthaburi':'จันทบุรี',
'Chachoengsao':'ฉะเชิงเทรา',
'Chonburi':'ชลบุรี',
'Chai Nat':'ชัยนาท',
'Chaiyaphum':'ชัยภูมิ',
'Chumphon':'ชุมพร',
'Chiang Rai':'เชียงราย',
'Chiang Mai':'เชียงใหม่',
'Trang':'ตรัง',
'Trat':'ตราด',
'Tak':'ตาก',
'Nakhon Nayok':'นครนายก',
'Nakhon Pathom':'นครปฐม',
'Nakhon Phanom':'นครพนม',
'Nakhon Ratchasima':'นครราชสีมา',
'Nakhon Si Thammarat':'นครศรีธรรมราช',
'Nakhon Sawan':'นครสวรรค์',
'Narathiwat':'นราธิวาส',
'Nan':'น่าน',
'Nonthaburi':'นนทบุรี',
'Bueng Kan':'บึงกาฬ',
'Buriram':'บุรีรัมย์',
'Pathum Thani':'ปทุมธานี',
'Prachuap Khiri Khan':'ประจวบคีรีขันธ์',
'Prachin Buri':'ปราจีนบุรี',
'Pattani':'ปัตตานี',
'Phayao':'พะเยา',
'Phang Nga':'พังงา',
'Phatthalung':'พัทลุง',
'Phichit':'พิจิตร',
'Phitsanulok':'พิษณุโลก',
'Phetchaburi':'เพชรบุรี',
'Phetchabun':'เพชรบูรณ์',
'Phrae':'แพร่',
'Phuket':'ภูเก็ต',
'Maha Sarakham':'มหาสารคาม',
'Mukdahan':'มุกดาหาร',
'Mae Hong Son':'แม่ฮ่องสอน',
'Yasothon':'ยโสธร',
'Yala':'ยะลา',
'Roi Et':'ร้อยเอ็ด',
'Ranong':'ระนอง',
'Rayong':'ระยอง',
'Ratchaburi':'ราชบุรี',
'Lopburi':'ลพบุรี',
'Lampang':'ลำปาง',
'Lamphun':'ลำพูน',
'Loei':'เลย',
'Sisaket':'ศรีสะเกษ',
'Songkhla':'สงขลา',
'Samut Prakan':'สมุทรปราการ',
'Samut Sakhon':'สมุทรสาคร',
'Samut Songkhram':'สมุทรสงคราม',
'Sa Kaeo':'สระแก้ว',
'Saraburi':'สระบุรี',
'Sing Buri':'สิงห์บุรี',
'Sukhothai':'สุโขทัย',
'Suphanburi':'สุพรรณบุรี',
'Surat Thani':'สุราษฎร์ธานี',
'Surin':'สุรินทร์',
'Satun':'สตูล',
'Nong Khai':'หนองคาย',
'Nong Bua Lamphu':'หนองบัวลำภู',
'Ang Thong':'อ่างทอง',
'Amnat Charoen':'อำนาจเจริญ',
'Udon Thani':'อุดรธานี',
'Uthai Thani':'อุทัยธานี',
'Uttaradit':'อุตรดิตถ์',
'Ubon Ratchathani':'อุบลราชธานี',
'Phra Nakhon Si Ayutthaya':'พระนครศรีอยุธยา',
'Overseas':'ต่างประเทศ'
}