provinces = [
    ["กระบี่", "Krabi"],
    ["กรุงเทพมหานคร", "Bangkok"],
    ["กาญจนบุรี", "Kanchanaburi"],
    ["กาฬสินธุ์", "Kalasin"],
    ["กำแพงเพชร", "Kamphaeng Phet"],
    ["ขอนแก่น", "Khon Kaen"],
    ["จันทบุรี", "Chanthaburi"],
    ["ฉะเชิงเทรา", "Chachoengsao"],
    ["ชลบุรี", "Chonburi"],
    ["ชัยนาท", "Chai Nat"],
    ["ชัยภูมิ", "Chaiyaphum"],
    ["ชุมพร", "Chumphon"],
    ["เชียงราย", "Chiang Rai"],
    ["เชียงใหม่", "Chiang Mai"],
    ["ตรัง", "Trang"],
    ["ตราด", "Trat"],
    ["ตาก", "Tak"],
    ["นครนายก", "Nakhon Nayok"],
    ["นครปฐม", "Nakhon Pathom"],
    ["นครพนม", "Nakhon Phanom"],
    ["นครราชสีมา", "Nakhon Ratchasima"],
    ["นครศรีธรรมราช", "Nakhon Si Thammarat"],
    ["นครสวรรค์", "Nakhon Sawan"],
    ["นราธิวาส", "Narathiwat"],
    ["น่าน", "Nan"],
    ["นนทบุรี", "Nonthaburi"],
    ["บึงกาฬ", "Bueng Kan"],
    ["บุรีรัมย์", "Buriram"],
    ["ปทุมธานี", "Pathum Thani"],
    ["ประจวบคีรีขันธ์", "Prachuap Khiri Khan"],
    ["ปราจีนบุรี", "Prachinburi"],
    ["ปัตตานี", "Pattani"],
    ["พะเยา", "Phayao"],
    ["พังงา", "Phang Nga"],
    ["พัทลุง", "Phatthalung"],
    ["พิจิตร", "Phichit"],
    ["พิษณุโลก", "Phitsanulok"],
    ["เพชรบุรี", "Phetchaburi"],
    ["เพชรบูรณ์", "Phetchabun"],
    ["แพร่", "Phrae"],
    ["ภูเก็ต", "Phuket"],
    ["มหาสารคาม", "Maha Sarakham"],
    ["มุกดาหาร", "Mukdahan"],
    ["แม่ฮ่องสอน", "Mae Hong Son"],
    ["ยโสธร", "Yasothon"],
    ["ยะลา", "Yala"],
    ["ร้อยเอ็ด", "Roi Et"],
    ["ระนอง", "Ranong"],
    ["ระยอง", "Rayong"],
    ["ราชบุรี", "Ratchaburi"],
    ["ลพบุรี", "Lopburi"],
    ["ลำปาง", "Lampang"],
    ["ลำพูน", "Lamphun"],
    ["เลย", "Loei"],
    ["ศรีสะเกษ", "Sisaket"],
    ["สงขลา", "Songkhla"],
    ["สมุทรปราการ", "Samut Prakan"],
    ["สมุทรสาคร", "Samut Sakhon"],
    ["สมุทรสงคราม", "Samut Songkhram"],
    ["สระแก้ว", "Sa Kaeo"],
    ["สระบุรี", "Saraburi"],
    ["สิงห์บุรี", "Sing Buri"],
    ["สุโขทัย", "Sukhothai"],
    ["สุพรรณบุรี", "Suphan Buri"],
    ["สุราษฎร์ธานี", "Surat Thani"],
    ["สุรินทร์", "Surin"],
    ["หนองคาย", "Nong Khai"],
    ["หนองบัวลำภู", "Nong Bua Lamphu"],
    ["อ่างทอง", "Ang Thong"],
    ["อำนาจเจริญ", "Amnat Charoen"],
    ["อุดรธานี", "Udon Thani"],
    ["อุทัยธานี", "Uthai Thani"],
    ["อุตรดิตถ์", "Uttaradit"],
    ["อุบลราชธานี", "Ubon Ratchathani"],
]

address={
'Krabi':'กระบี่',
'Bangkok':'กรุงเทพมหานคร',
'Kanchanaburi':'กาญจนบุรี',
'Kalasin':'กาฬสินธุ์',
'Kamphaeng Phet':'กำแพงเพชร',
'Khon Kaen':'ขอนแก่น',
'Chanthaburi':'จันทบุรี',
'Chachoengsao':'ฉะเชิงเทรา',
'Chonburi':'ชลบุรี',
'Chai Nat':'ชัยนาท',
'Chaiyaphum':'ชัยภูมิ',
'Chumphon':'ชุมพร',
'Chiang Rai':'เชียงราย',
'Chiang Mai':'เชียงใหม่',
'Trang':'ตรัง',
'Trat':'ตราด',
'Tak':'ตาก',
'Nakhon Nayok':'นครนายก',
'Nakhon Pathom':'นครปฐม',
'Nakhon Phanom':'นครพนม',
'Nakhon Ratchasima':'นครราชสีมา',
'Nakhon Si Thammarat':'นครศรีธรรมราช',
'Nakhon Sawan':'นครสวรรค์',
'Narathiwat':'นราธิวาส',
'Nan':'น่าน',
'Nonthaburi':'นนทบุรี',
'Bueng Kan':'บึงกาฬ',
'Buriram':'บุรีรัมย์',
'Pathum Thani':'ปทุมธานี',
'Prachuap Khiri Khan':'ประจวบคีรีขันธ์',
'Prachinburi':'ปราจีนบุรี',
'Pattani':'ปัตตานี',
'Phayao':'พะเยา',
'Phang Nga':'พังงา',
'Phatthalung':'พัทลุง',
'Phichit':'พิจิตร',
'Phitsanulok':'พิษณุโลก',
'Phetchaburi':'เพชรบุรี',
'Phetchabun':'เพชรบูรณ์',
'Phrae':'แพร่',
'Phuket':'ภูเก็ต',
'Maha Sarakham':'มหาสารคาม',
'Mukdahan':'มุกดาหาร',
'Mae Hong Son':'แม่ฮ่องสอน',
'Yasothon':'ยโสธร',
'Yala':'ยะลา',
'Roi Et':'ร้อยเอ็ด',
'Ranong':'ระนอง',
'Rayong':'ระยอง',
'Ratchaburi':'ราชบุรี',
'Lopburi':'ลพบุรี',
'Lampang':'ลำปาง',
'Lamphun':'ลำพูน',
'Loei':'เลย',
'Sisaket':'ศรีสะเกษ',
'Songkhla':'สงขลา',
'Samut Prakan':'สมุทรปราการ',
'Samut Sakhon':'สมุทรสาคร',
'Samut Songkhram':'สมุทรสงคราม',
'Sa Kaeo':'สระแก้ว',
'Saraburi':'สระบุรี',
'Sing Buri':'สิงห์บุรี',
'Sukhothai':'สุโขทัย',
'Suphan Buri':'สุพรรณบุรี',
'Surat Thani':'สุราษฎร์ธานี',
'Surin':'สุรินทร์',
'Nong Khai':'หนองคาย',
'Nong Bua Lamphu':'หนองบัวลำภู',
'Ang Thong':'อ่างทอง',
'Amnat Charoen':'อำนาจเจริญ',
'Udon Thani':'อุดรธานี',
'Uthai Thani':'อุทัยธานี',
'Uttaradit':'อุตรดิตถ์',
'Ubon Ratchathani':'อุบลราชธานี'
}
print(address['Krabi']);